### ISSUE TITLE
extendedStopwords

### ISSUE THREAD

**Issue by cpsievert** [OhLookCake/xkcd-Topics#2]
I'm just curious why you decided to include the stop-words in [this file](https://github.com/CabbagesAndKings/xkcd-Topics/blob/master/scripts/extendedStopwords.R). I have very little experience with pre-processing text, so any sort of justification you have will work for me :)

**Comment by OhLookCake** [comment]
The reason is hardly technical - It's a pretty long list and would have been distracting as part of the main code. So I isolated it out into a different file. 
Like it says in the comment in the code:
#I've pulled this two-line piece out because it was making the main code difficult to parse, and ugly to look at

**Comment by cpsievert** [comment]
I understand the comment, but I don't understand why someone would do all that typing without a reason :)

Did you get that list from somewhere? Or is it something you cooked up yourself? FYI, I decided to add "aaaaaa","aaaaaaa","aaaaaaaa", "aaaaaaaaaa" to this list. I will be pushing some changes to my forked version fairly soon which you can check out.

**Comment by OhLookCake** [comment]
Oh. Okay. I didn't type it out - I used one of the freely available lists from another text-processing project. The _tm_ package comes with it's own list of stopwords built right in, but the list is fairly limited, and when I tried the code with that list only, I still kept getting some pretty common English words as the dominant terms in the topics. So I appended this longer list.
